import cron from 'node-cron';
import { prisma } from '../lib/prisma.js';
import { campaignDispatchQueue, healthComputeQueue } from '../queues/queues.js';
import { generateCampaignVariants } from '../ai/CampaignWriter.js';
import { SegmentEngine } from '../services/SegmentEngine.js';

/**
 * Monthly Campaign Scheduler
 * Fires on 1st of every month at 9:00 AM IST.
 * Auto-generates and launches campaigns for all auto-scheduled segments.
 */
export async function initScheduler() {
  // Monthly auto-campaign: 1st of every month at 9:00 AM
  cron.schedule('0 9 1 * *', async () => {
    console.log('[Scheduler] 🗓️  Monthly auto-campaign run starting...');
    await runMonthlyCampaigns();
  }, { timezone: 'Asia/Kolkata' });

  // Accelerated health score recomputation: Every 5 minutes (for testing)
  cron.schedule('*/5 * * * *', async () => {
    console.log('[Scheduler] 🔄 Accelerated health score recomputation...');
    await healthComputeQueue.add('nightly-health', {}, {
      jobId: `health-${new Date().toISOString()}`,
    });
  });

  // Abandoned Cart Agent: Every 4 hours
  cron.schedule('0 */4 * * *', async () => {
    console.log('[Scheduler] 🛒 Checking for abandoned carts...');
    await checkAbandonedCarts();
  });

  console.log('✅ Scheduled jobs:');
  console.log('   - Monthly auto-campaigns: 1st of month @ 9:00 AM IST');
  console.log('   - Health scores: Every 5 minutes (Test Mode)');
  console.log('   - Abandoned cart agent: Every 4 hours (and manual)');
}

export async function checkAbandonedCarts() {
  const tenMinutesAgo = new Date(Date.now() - 10 * 60 * 1000);

  try {
    // Find ACTIVE carts older than 10 mins
    const abandonedCarts = await prisma.cart.findMany({
      where: {
        status: 'ACTIVE',
        lastActiveAt: {
          lte: tenMinutesAgo,
        },
      },
      include: {
        customer: true,
      }
    });

    if (abandonedCarts.length > 0) {
      console.log(`[Cart Agent] Found ${abandonedCarts.length} newly abandoned carts.`);

      // Update their status
      await prisma.cart.updateMany({
        where: {
          id: {
            in: abandonedCarts.map(c => c.id)
          }
        },
        data: {
          status: 'ABANDONED'
        }
      });

      // Simulate sending nudges
      for (const cart of abandonedCarts) {
        console.log(`[Cart Agent] 📧 SIMULATING NUDGE EMAIL to ${cart.customer.email} for cart worth ₹${cart.totalValue}`);
      }
    }
  } catch (error) {
    console.error('[Cart Agent] ❌ Error checking abandoned carts:', error);
  }
}

async function runMonthlyCampaigns() {
  const autoSegments = await prisma.segment.findMany({
    where: { isAutoScheduled: true },
  });

  if (autoSegments.length === 0) {
    console.log('[Scheduler] No auto-scheduled segments found');
    return;
  }

  const monthLabel = new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' });

  for (const segment of autoSegments) {
    try {
      console.log(`[Scheduler] Processing segment: "${segment.name}"`);

      // Compute current segment members
      const customers = await SegmentEngine.compute(segment.filterRules as never);
      if (customers.length === 0) {
        console.log(`[Scheduler] Segment "${segment.name}" has 0 customers, skipping`);
        continue;
      }

      // Update segment customer count
      await prisma.segment.update({
        where: { id: segment.id },
        data: { customerCount: customers.length, lastComputedAt: new Date() },
      });

      // Generate message variants via Gemini
      const variantsResult = await generateCampaignVariants({
        objective: segment.autoObjective || 'Engage customers and drive repeat purchases',
        channel: segment.preferredChannel,
        segmentDescription: segment.description || segment.name,
        segmentSize: customers.length,
      });

      // Create campaign
      const campaign = await prisma.campaign.create({
        data: {
          name: `Auto: ${segment.name} — ${monthLabel}`,
          description: `Automatically generated monthly campaign for ${monthLabel}`,
          segmentId: segment.id,
          channel: segment.preferredChannel,
          status: 'RUNNING',
          isAutoGenerated: true,
          launchedAt: new Date(),
          variants: {
            create: variantsResult.variants.map(v => ({
              label: v.label,
              angle: v.angle,
              subject: v.subject,
              body: v.body,
              targetProfile: v.targetProfile,
            })),
          },
        },
        include: { variants: true },
      });

      // Queue campaign dispatch
      await campaignDispatchQueue.add(
        `dispatch:${campaign.id}`,
        {
          campaignId: campaign.id,
          customerIds: customers.map(c => c.id),
          channel: segment.preferredChannel,
          variantIds: campaign.variants.map(v => v.id),
        },
      );

      console.log(`[Scheduler] ✅ Auto-campaign "${campaign.name}" launched for ${customers.length} customers`);
    } catch (err) {
      console.error(`[Scheduler] ❌ Failed for segment "${segment.name}":`, err);
    }
  }
}
